# 쿠폰 발급 배치 크기 (OOM 방지)
coupon.batch-size=1000

# AWS S3 설정 (실제 AWS 환경)
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:coupon-admin-prod}
aws.s3.region=${AWS_REGION:ap-northeast-2}
aws.s3.endpoint-url=
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
